var chart = AmCharts.makeChart("speakers_chart", {
    "type": "pie",
	"theme": "none",
    "dataProvider": [
      { "speaker": "Anders fisher"       , "talks": 16},
      { "speaker": "Paul Hutson"         , "talks":  6},
      { "speaker": "Steve Butterworth"   , "talks":  4},
      { "speaker": "David Kirkby"        , "talks":  3},
      { "speaker": "Karl Dawson"         , "talks":  3},
      { "speaker": "Kerry Buckley"       , "talks":  3},
      { "speaker": "Sean Dunn"           , "talks":  3},
      { "speaker": "Max Shelley"         , "talks":  2},
      { "speaker": "Matthew Bennett"     , "talks":  2},
      { "speaker": "Ross Scrivener"      , "talks":  2},
      { "speaker": "Robert Lee Cann"     , "talks":  2},
      { "speaker": "Adam Whittingham"    , "talks":  2},
      { "speaker": "Dan Higham"          , "talks":  1},
      { "speaker": "Tom Crinson"         , "talks":  1},
      { "speaker": "Robin Meehan"        , "talks":  1},
      { "speaker": "Jason Van Lue"       , "talks":  1},
      { "speaker": "Richard Astbury"     , "talks":  1},
      { "speaker": "Chris Filip"         , "talks":  1},
      { "speaker": "Toby Hope"           , "talks":  1},
      { "speaker": "Carl Farmer"         , "talks":  1},
      { "speaker": "Elliott Stoneham"    , "talks":  1},
      { "speaker": "David Hurren"        , "talks":  1},
      { "speaker": "Matthew Applegate"   , "talks":  1},
      { "speaker": "Shaun Macdonald"     , "talks":  1},
      { "speaker": "Tom Chinery"         , "talks":  1}
    ],
    "valueField": "talks",
    "titleField": "speaker"
});
